* advange
https://www.zhihu.com/question/40492181



* defect

多人协作





轻量级的启动环境

3、编辑器未和执行环境分离，若要DEBUG，必须启动U3D编辑器。 而很多时候，对于程序员来说，是不需要的。 它们只是想改改代码，
然后编译，执行。 或许，U3D可以通过命令行提供一个较轻量的启动环境。 





纹理压缩



游戏包大小

need support custom package



ui:
support extend ui


api设计:

修改rectTransform的宽高，找了半天，属性函数翻来覆去测试都tm不行，原来在sizeDllta里，还不能直接修改高度，还要new一个v2，
c,浪费我多少时间，想要深入点使用就会发现类似的问题。这些最基本的东西，时间都浪费这这些方面，游戏结果，动画效果就没有精力
搞了。以前对他还存在的好感被一点点恶心掉了。好怀念as3API结构清晰明快，属性函数使用方便，事件处理简单，引用子项非常方
便。。。不说了 




开源：
做大项目来说，没有源代码，遇到坑没办法自己填，只能绕路。




支持中文


性能问题



资源部分:

作者：钱康来
链接：https://www.zhihu.com/question/265610021/answer/296708358
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

目前我们遇到的最大问题是资源部分导入的原始资源管理打包时的资源管理第二点前面也有答主提到了。目前Unity里两条路，Resources
的话官方本来就不推荐使用[1]: Best Practices for the Resources System——Don't use it.AssetBundle这块也有不少的坑。目前的
API隐藏了大量的细节，导致在控制粒度上比较粗[2]；在控制包体个数和大小上各个项目需要自己去平衡；做不到一个版本仓库稳定打出
精确一致的AB(别说不同机器，同一台机器有时候都会有细微差别...)；打包速度也比较捉急；增量打包完全是靠manifest，有时候甚至
会出错。ps. 至于内存管理、异步加载API不好用这种我们自己写代码能解决的我就不算在上面了……第一点是在我们项目不断推进中遇到
的问题：Unity的资源管理是直接导入原始资源(fbx/tga/甚至有时候美术会给你塞一些惊喜譬如psd进来...)，但是如果需要扣一些细节
的时候就非常捉急了...FBX里的Mesh/Animation Clip无法修改，如果要做一些优化就令人头大[3]Main Asset + Sub Asset的概念导致没
法更细的控制加载和释放每台机器遇到新资源都会走ImportAsset，这个有小概率遇到冲突(在使用Spine/Live2d这种插件的时候遇到过几
次)目前我们正在参考UE4，剥离原始资源(只在美术机器上留一份)，在项目里使用生成的对应asset或其他Unity内置的格式。这个比分离
美术/程序两个工程然后AB来传递的好处就是方便一些修改和使用。ps. 评论区补充的资源检查我们目前是分为两部分，一个是导入的时
候自动检查(譬如关掉Import Material之类的)；另一个是用工具定时扫描自定义规则。 



Unity的最大的坑莫过于AssetBundle，各种内存泄露、各种资源冗余、各种异步加载坑爹。打包的时候需要买个垃圾桶、不然内存保证不
够用……增量无法删除老资源。 



AssetBundle的坑我就不重复了。资源导入机制也很坑，开发途中难免转平台，稍微大一点的项目资源重新导入需要等非常久！即便不转
平台，第一次打开大项目也是很痛苦。想不通为什么一张几百x几百的图片unity竟然要处理几秒钟的时间。。这种处理速度完全不能接
受。。。 

作者：SNAKE
链接：https://www.zhihu.com/question/265610021/answer/297294016
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。





脚本执行顺序

脚本执行顺序也是非常奇怪的东西，项目脚本一多起来、加上使用第三方插件的脚本，微妙的执行顺序调整最后会让你头疼。有时想完全
手动控制更新顺序，但有些 Unity 功能的实现又必须依赖这套 MonoBehaviour 事件系统（比如动画相关的实现）。Unity 应该减少引擎
层面对上层逻辑的控制，将它们公开给开发者自己去管理。就像新的 ScriptableRenderPipeline 那样。 

作者：匿名用户
链接：https://www.zhihu.com/question/265610021/answer/297927552
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。









烘焙灯光极其慢
